version: "3.8"
services:
  lib:
    build:
      context: .
      args:
        SKIP_BUNDLER: $SKIP_BUNDLER
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    stdin_open: true
    env_file: .env
