version: "3.8"
services:
  lib:
    build:
      context: .
      args:
        SKIP_BUNDLER: $SKIP_BUNDLER
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    stdin_open: true
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql:5.7.32
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  db-data:
