version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.1
        environment:
          BUNDLE_APP_CONFIG: .bundle
          SQL_DEBUG: 0
          DB_PASSWORD: 1234
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          RAILS_ENV: test

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: rails_utils_test

    steps:
      - checkout

      - restore_cache:
          keys:
            - rails-utils-gems-{{ checksum "Gemfile.lock" }}
            - rails-utils-gems-

      - run:
          name: install gems
          command: |
            bundle config set --local path vendor/bundle
            bundle install

      - save_cache:
          key: rails-utils-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: lint
          command: bundle exec rubocop

      - run:
          name: wait for database
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: prepare database
          command: bundle exec rake db:setup

      - run:
          name: test
          command: bundle exec rake spec
